### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by ProtoGhost** [AerWyn81/AParkour#11] opened 2022-07-26 06:06 UTC
[08:01:50 ERROR]: Could not pass event PlayerChangedWorldEvent to AParkour v3.5.5
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[server.jar:git-PaperSpigot-2894af04d]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[server.jar:git-PaperSpigot-2894af04d]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[server.jar:git-PaperSpigot-2894af04d]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) [server.jar:git-PaperSpigot-2894af04d]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) [server.jar:git-PaperSpigot-2894af04d]
        at net.minecraft.server.v1_8_R3.PlayerList.moveToWorld(PlayerList.java:644) [server.jar:git-PaperSpigot-2894af04d]
        at org.bukkit.craftbukkit.v1_8_R3.entity.CraftPlayer.teleport(CraftPlayer.java:568) [server.jar:git-PaperSpigot-2894af04d]
        at org.bukkit.craftbukkit.v1_8_R3.entity.CraftEntity.teleport(CraftEntity.java:236) [server.jar:git-PaperSpigot-2894af04d]
        at com.fun.spawntp.Main.onJoin(Main.java:85) [SonezSpawn.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_312]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_312]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_312]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_312]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300) [server.jar:git-PaperSpigot-2894af04d]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) [server.jar:git-PaperSpigot-2894af04d]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [server.jar:git-PaperSpigot-2894af04d]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) [server.jar:git-PaperSpigot-2894af04d]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) [server.jar:git-PaperSpigot-2894af04d]
        at net.minecraft.server.v1_8_R3.PlayerList.onPlayerJoin(PlayerList.java:314) [server.jar:git-PaperSpigot-2894af04d]
        at net.minecraft.server.v1_8_R3.PlayerList.a(PlayerList.java:173) [server.jar:git-PaperSpigot-2894af04d]
        at net.minecraft.server.v1_8_R3.LoginListener.b(LoginListener.java:144) [server.jar:git-PaperSpigot-2894af04d]
        at net.minecraft.server.v1_8_R3.LoginListener.c(LoginListener.java:54) [server.jar:git-PaperSpigot-2894af04d]
        at net.minecraft.server.v1_8_R3.NetworkManager.a(NetworkManager.java:231) [server.jar:git-PaperSpigot-2894af04d]
        at net.minecraft.server.v1_8_R3.ServerConnection.c(ServerConnection.java:148) [server.jar:git-PaperSpigot-2894af04d]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:875) [server.jar:git-PaperSpigot-2894af04d]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [server.jar:git-PaperSpigot-2894af04d]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [server.jar:git-PaperSpigot-2894af04d]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [server.jar:git-PaperSpigot-2894af04d]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_312]
Caused by: java.lang.NullPointerException
        at me.davidml16.aparkour.managers.StatsHologramManager.haveParkourData(StatsHologramManager.java:92) ~[?:?]
        at me.davidml16.aparkour.managers.StatsHologramManager.reloadStatsHologram(StatsHologramManager.java:72) ~[?:?]
        at me.davidml16.aparkour.managers.StatsHologramManager.reloadStatsHolograms(StatsHologramManager.java:63) ~[?:?]
        at me.davidml16.aparkour.events.Event_Others.onWorld(Event_Others.java:146) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_312]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_312]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_312]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_312]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300) ~[server.jar:git-PaperSpigot-2894af04d]
        ... 28 more

**Comment by AerWyn81** [comment] 2022-07-26 22:39
Hi, I can't reproduce this issue. 

-> Do you have HolographicDisplays installed and no related error?
-> Do you have your parkour correctly setup?

Could you provide me a way to reproduce it?

Thanks.

**Comment by AerWyn81** [comment] 2022-08-30 23:03
Potentially fixed in the version [3.7.9](https://github.com/AerWyn81/AParkour/releases/tag/3.7.9)

Re-open the issue if the issue still persist

Thanks for your report!

**Closed as completed by AerWyn81** 2022-08-30 23:03 UTC
